assetic:
  debug:          "%kernel.debug%"
  use_controller: false
  bundles:        ['ITFAdminBundle']
  filters:
      cssrewrite: ~
  assets:
      admin_css:
          inputs:
              - 'bundles/alidatatable/third-party/bootstrap/css/bootstrap.min.css'
              - 'bundles/itfadmin/inspinia/font-awesome/css/font-awesome.css'
              - 'bundles/alidatatable/css/dataTables.bootstrap.min.css'
      admin_js:
          inputs:
              - 'bundles/alidatatable/js/jquery.min.js'
              - 'bundles/itfadmin/js/modernizr-2.8.3.min.js'
              - 'bundles/itfadmin/js/respond.js'
              - 'bundles/itfadmin/plugins/bs-custom/js/bs-custom.min.js'
              - 'bundles/alidatatable/js/jquery.dataTables.min.js'
              - 'bundles/alidatatable/js/dataTables.bootstrap.min.js'

      admin_edit_css:
          inputs:
                - 'bundles/itfadmin/inspinia/css/plugins/dataTables/dataTables.bootstrap.css'
                - 'bundles/itfadmin/inspinia/css/plugins/dataTables/dataTables.responsive.css'
                - 'bundles/itfadmin/inspinia/css/plugins/dataTables/dataTables.tableTools.min.css'
                - 'bundles/itfadmin/inspinia/css/plugins/select2/select2.min.css'
                - 'bundles/itfadmin/inspinia/css/plugins/colorpicker/bootstrap-colorpicker.min.css'
                - 'bundles/itfadmin/inspinia/css/plugins/datapicker/datepicker3.css'
                - 'bundles/itfadmin/inspinia/css/plugins/datapicker/bootstrap-datetimepicker.css'

      admin_edit_js:
          inputs:
                - 'bundles/itfadmin/inspinia/js/plugins/dataTables/jquery.dataTables.js'
                - 'bundles/itfadmin/inspinia/js/plugins/dataTables/dataTables.bootstrap.js'
                - 'bundles/itfadmin/inspinia/js/plugins/dataTables/dataTables.responsive.js'
                - 'bundles/itfadmin/inspinia/js/plugins/dataTables/dataTables.tableTools.min.js'
                - 'bundles/itfadmin/inspinia/js/plugins/dataTables/dataTables.tableTools.min.js'
                - 'bundles/itfadmin/inspinia/js/plugins/select2/select2.full.min.js'
                - 'bundles/itfadmin/inspinia/js/plugins/colorpicker/bootstrap-colorpicker.min.js'
                - 'bundles/itfadmin/inspinia/js/plugins/datapicker/bootstrap-datepicker.js'
                - 'bundles/itfadmin/inspinia/js/plugins/fullcalendar/moment.min.js'
                - 'bundles/itfadmin/inspinia/js/plugins/datapicker/bootstrap-datetimepicker.min.js'

      bootstrap_glyphicons_ttf:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
          output: "/fonts/glyphicons-halflings-regular.ttf"
      bootstrap_glyphicons_eot:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
          output: "/fonts/glyphicons-halflings-regular.eot"
      bootstrap_glyphicons_svg:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
          output: "/fonts/glyphicons-halflings-regular.svg"
      bootstrap_glyphicons_woff:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
          output: "/fonts/glyphicons-halflings-regular.woff"
      bootstrap_glyphicons_woff2:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
          output: "/fonts/glyphicons-halflings-regular.woff2"