assetic:
  debug:          "%kernel.debug%"
  use_controller: false
  bundles:        ['ITFAdminBundle']
  filters:
      cssrewrite: ~
  assets:
      admin_css:
          inputs:
              - 'bundles/alidatatable/third-party/bootstrap/css/bootstrap.min.css'
              - 'bundles/alidatatable/css/dataTables.bootstrap.min.css'
              - '@ITFAdminBundle/Resources/public/css/helper.css'
              - '@ITFAdminBundle/Resources/public/css/admin.css'
      admin_js:
          inputs:
              - 'bundles/alidatatable/js/jquery.min.js'
              - '@ITFAdminBundle/Resources/public/js/modernizr-2.8.3.min.js'
              - '@ITFAdminBundle/Resources/public/js/respond.js'
              - '@ITFAdminBundle/Resources/public/plugins/bs-custom/js/bs-custom.min.js'
              - 'bundles/alidatatable/js/jquery.dataTables.min.js'
              - 'bundles/alidatatable/js/dataTables.bootstrap.min.js'

      bootstrap_glyphicons_ttf:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
          output: "fonts/glyphicons-halflings-regular.ttf"
      bootstrap_glyphicons_eot:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
          output: "fonts/glyphicons-halflings-regular.eot"
      bootstrap_glyphicons_svg:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
          output: "fonts/glyphicons-halflings-regular.svg"
      bootstrap_glyphicons_woff:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
          output: "fonts/glyphicons-halflings-regular.woff"
      bootstrap_glyphicons_woff2:
          inputs:
              - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
          output: "fonts/glyphicons-halflings-regular.woff2"