services:
    itf.admin.factory:
        class: ITF\AdminBundle\Admin\AdminFactory

    itf.admin_helper:
        class:        ITF\AdminBundle\Admin\AdminHelper
        arguments:    [ "@doctrine.orm.entity_manager", "@service_container" ]

    itf.admin.config:
        class: ITF\AdminBundle\Admin\Configuration
        arguments: [ @service_container ]

    itf.admin.form.helper:
        class: ITF\AdminBundle\Admin\Form\FormHelper
        arguments: [ @service_container ]


    # listener
    itf.listener.orm.logger:
        class: ITF\AdminBundle\EventListener\LoggingListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }


    # KernelRequest listener
    extension.listener:
        class: ITF\AdminBundle\EventListener\DoctrineExtensionListener
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            # translatable sets locale after router processing
            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }

            # translatable sets locale such as default application locale before command execute
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: -10 }

    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setDefaultLocale, [ %locale% ] ]
            - [ setTranslationFallback, [ false ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
